services:
  api:
    build:
        context: ..
        dockerfile: FurnitureStore.API/Dockerfile
    ports:
      - "7070:443"
      - "5050:80"
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Test1234!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/cert.pfx
      - ASPNETCORE_Environment=Production
      - FurnitureStoreAPI_ConnectionStrings__FurnitureStoreDB=Server=db;Port=5432;Database=furniture_store;User ID=fs_admin;Password=store1234!;
    depends_on:
      db:
        condition: service_started

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=fs_admin
      - POSTGRES_PASSWORD=store1234!
      - POSTGRES_DB=furniture_store
    ports:
      - "5432:5432"
    volumes:
      - postgresdbdata:/data/db

      
volumes:
  postgresdbdata:

  


